version: '3.8'

services:
  fastapi:
    build:
      context: .
      target: fastapi
    env_file:
      - .env
    networks:
      - weather-network
    expose:
      - "8000"

  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - weather-network

networks:
  weather-network:
